### ISSUE TITLE
Uncollaberate DarkGabbz

### ISSUE THREAD

**Issue by Kingy34** [Calafska/Username-Bot#12]
DarkGabbz is a cyberbuly

**Comment by Kingy34** [comment]
oh, and has never added anything interesting.

**Comment by cheuble** [comment]
no u

**Comment by Kingy34** [comment]
He's cause dnothing but chaos

**Comment by Calafska** [comment]
oh shit

**Comment by cheuble** [comment]
that "chaos" site :Lenny:

**Comment by Calafska** [comment]
gonna look into the code now senpais

**Comment by Kingy34** [comment]
What the fuck does this have to do with DarkGabbz

**Comment by Calafska** [comment]
wow

**Comment by Kingy34** [comment]
Create a new issue if you want to talk about 'code', this is about DarkGabbz

**Comment by Calafska** [comment]
wtf are we doing with the comments lmao

**Comment by Kingy34** [comment]
You changed the subject.

**Comment by Calafska** [comment]
@Kingy34 HE IS THE BUG <3

**Comment by Kingy34** [comment]
ban him

**Comment by cheuble** [comment]
This is not a chat lmao

**Comment by Kingy34** [comment]
ikr

**Comment by Kingy34** [comment]
mr 'helper' over here is not sorting this out

**Comment by DarkGabbz** [comment]
ok

**Comment by cheuble** [comment]
#discordbotdrama

**Comment by DarkGabbz** [comment]
ok

**Comment by Kingy34** [comment]
@DarkGabbz You should be restrained away from all discord sources

**Comment by Kingy34** [comment]
@Calafska do something

**Comment by Kingy34** [comment]
frfs

**Comment by Kingy34** [comment]
Holy fuck can someone helpfull just sort this out or anything, even the owner isn't doing shit

**Comment by Calafska** [comment]
sorry

**Comment by Calafska** [comment]
needed to do some shit for school

**Comment by Kingy34** [comment]
Can you do something?

**Comment by Calafska** [comment]
yeah

**Comment by Calafska** [comment]
of course

**Comment by Kingy34** [comment]
thank you

**Comment by DarkGabbz** [comment]
@Kingy34 
![grafik](https://cloud.githubusercontent.com/assets/21977338/22307447/44b5fff6-e343-11e6-97ac-3820e4aaa73e.png)

**Comment by Calafska** [comment]
no problem :)
also I didnt knew that you were still intrested in the project <3

**Comment by Kingy34** [comment]
Is he gone?

**Comment by Calafska** [comment]
yup

**Comment by Kingy34** [comment]
THANK YOU <3

**Comment by cheuble** [comment]
👌
